### ISSUE TITLE
useAdoptOpenJdk8 method has not been published to the maven repository

### ISSUE THREAD

**Issue by abauman-7signal** [rmee/gradle-plugins#28]
I followed the README.md documentation to use the newer `useAdoptOpenJdk8` method. However, it was committed to `master` but hasn't been published to the maven repository.

**Comment by remmeier** [comment]
Hi, should be available as it has been committed in January. Where have you been looking? bintray latest, bintray stable or the Gradle repo?

**Comment by hakanai** [comment]
Same with 11.

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method useAdoptOpenJdk11() for arguments [11.0.5+10] on object of type com.github.rmee.jdk.bootstrap.JdkBootstrapExtension.
```

In build script:

```gradle
plugins {
  id 'com.github.rmee.jdk-bootstrap' version '1.0.20190725142159'
}
jdk {
    useAdoptOpenJdk11('11.0.5+10')
}
```

Latest version is 1.0.20190725142159, created 26 July 2019.
https://plugins.gradle.org/plugin/com.github.rmee.jdk-bootstrap


Also tried:

```gradle
buildscript {
    dependencies {
        classpath "gradle.plugin.com.github.rmee:jdk-bootstrap:1.0.20190725142159"
    }
}

apply plugin: "com.github.rmee.jdk-bootstrap"
jdk {
    useAdoptOpenJdk11('11.0.5+10')
}
```

**Comment by remmeier** [comment]
those are very recent changes, should have mentioned in in the README. Can do a public release after https://github.com/rmee/gradle-plugins/issues/34 has been addressed.

**Comment by hakanai** [comment]
Actually I got denied using the utility method anyway because we want all binaries to come from the local artifact server anyway, so it turns out not to be a problem for us.

**Comment by remmeier** [comment]
you can configure it to fetch it locally from any location. those useAdtopt method are just one example/shortcut

**Comment by vojkny** [comment]
```
plugins {
  id 'com.github.rmee.jdk-bootstrap' version '1.0.20190725142159'
}
jdk {
    useAdoptOpenJdk11('11.0.5+10')
}
``` 

I tried exactly this and it seems it is completely and silently ignored. Is this in default gradle repo?

Edit: It seems the method is already there (if I change it to `useAdoptOpenJdk11XX` it fails). - but it has no effect, I still see:

```
Process 'command '/usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home/bin/java''
```
